"use client";

/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HbEPCKCUZBm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button";
import {gql, useQuery} from "@apollo/client";
const GET_ITEMS = gql`
  query GetItems {
    item {
      id
      name
      desc
      image
      price
      size_options
      updated_at
      created_at
      color_options
      }
    }
  `;

export default function ItemComponent() {
const { data } = useQuery(GET_ITEMS);
const items = data?.item;
if (!items) {
 return null;
}
  return (
    <div className="grid grid-cols-4 gap-8">
    {items.map((item:any) => <div className="space-y-4">
            <img
              alt="Classic Logo Ringer Tee White"
              className="w-full"
              height="200"
              src="\macbook.jpeg"
              style={{
                aspectRatio: "150/200",
                objectFit: "cover",
              }}
              width="150"
            />
            <div className="space-y-2">
              <h3 className="text-lg font-semibold">{item.name}</h3>
              <p className="text-sm">{item.desc}</p>
              <div className="space-y-1">
                <span className="text-xs line-through text-gray-500">10,000,000원</span>
                <span className="text-xl font-bold">{item.price}</span>
                <span className="text-sm font-semibold text-red-500">10%</span>
              </div>
              <Button className="w-full" variant="outline">
                쿠폰 받기
              </Button>
              <div className="flex justify-between items-center">
                <HeartIcon className="w-6 h-6 text-gray-400" />
                <span className="text-xs">13,760</span>
                <ShareIcon className="w-6 h-6 text-gray-400" />
                <span className="text-xs">656</span>
              </div>
            </div>
          </div>
    )}
    </div>
  )
}

function HeartIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
    </svg>
  )
}


function ShareIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
      <polyline points="16 6 12 2 8 6" />
      <line x1="12" x2="12" y1="2" y2="15" />
    </svg>
  )

}